# GitHubActions for testing
# read the docs: https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow

name: TESTS DONE

on:
  workflow_run:
    workflows:
      - TESTS RUN
    types:
      - completed

env:
  FOO_ENV_VAR: tests_done

jobs:
  process-reports:
    name: process artifact reports
    runs-on: ubuntu-latest
    steps:
      - name: fetch reports
        # see https://github.com/actions/download-artifact
        uses: actions/download-artifact@v2
        with:
          name: reports
          path: ./reports/
      - name: read dummy reports
        run: cat reports/date

  debug:
    name: DEBUG
    runs-on: ubuntu-latest
    steps:
      # see https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#contexts
      - run: echo "$CONTEXT"
        name: github
        env:
          CONTEXT:  ${{ toJson(github) }}
      - run: echo "$CONTEXT"
        name: env
        env:
          CONTEXT:  ${{ toJson(env) }}
      - run: echo "$CONTEXT"
        name: runner
        env:
          CONTEXT:  ${{ toJson(runner) }}
      - run: echo "$CONTEXT"
        name: strategy
        env:
          CONTEXT:  ${{ toJson(strategy) }}
      - run: echo "$CONTEXT"
        name: matrix
        env:
          CONTEXT:  ${{ toJson(matrix) }}
      - run: echo "$CONTEXT"
        name: needs
        env:
          CONTEXT:  ${{ toJson(needs) }}
      - run: echo "$CONTEXT"
        name: secrets
        env:
          CONTEXT:  ${{ toJson(secrets) }}
